/**
 * ReportDetail fixtures for NEXT_PUBLIC_USE_MOCKS mode.
 * Vocabulary is pulled from aiml/configs/ontology.yaml. Spans are exact —
 * generated by buildReport() from inline markers, never hand-counted.
 *
 * Coverage:
 *  r-4401  HIGH_CONF_SIF        Energy Isolation, clean, overlapping spans
 *  r-4402  HIGH_CONF_NON_SIF    confirmed_present barrier, no_exposure
 *  r-4403  LOW_CONF_REVIEW      uncertain, code-mixed text
 *  r-4404  NEEDS_MORE_INFO      sparse report, several span:null fields
 *  r-4405  HIGH_CONF_SIF        Working at Height, barrier absent
 *  r-4406  HIGH_CONF_SIF        Confined Space, hazard present -> BUGGY hazard shape
 *
 *  Review-queue fixtures (LOW_CONF_REVIEW / NEEDS_MORE_INFO, review_status pending):
 *  r-4410  LOW_CONF_REVIEW     Line of Fire, oldest in queue
 *  r-4411  NEEDS_MORE_INFO     Driving, sparse
 *  r-4412  LOW_CONF_REVIEW     Confined Space — a second reviewer already logged a
 *                              matching correction; the next matching action promotes it
 *  r-4413  LOW_CONF_REVIEW     Safe Mechanical Lifting
 */
import type { ReportDetail } from "../schemas";
import { buildReport, spanOf, type BuiltSpan } from "./build";

function spanField(spans: BuiltSpan[], field: string, confidence: number) {
  const s = spans.find((x) => x.field === field);
  return s
    ? { text: s.text, span: s.span, confidence }
    : null;
}

function labelField(
  label: string,
  confidence: number,
  span: [number, number] | null = null
) {
  return span ? { label, confidence, span } : { label, confidence };
}

/* ------------------------------------------------------------------ r-4401 */
const b1 = buildReport(
  `During {{activity|maintenance on process equipment}} at Rig 4, {{exposure|a worker was standing within the immediate hazard zone}}. {{barrier_status|Isolation status was not clearly confirmed by the crew}}. No injury occurred.`
);
// deliberate partial overlap: "immediate hazard zone" also marked as hazard,
// nested inside the exposure span.
const hazardStart = b1.text.indexOf("immediate hazard zone");
const overlapSpans: BuiltSpan[] = [
  ...b1.spans,
  {
    field: "hazard",
    text: "immediate hazard zone",
    span: [hazardStart, hazardStart + "immediate hazard zone".length],
    confidence: 0.83,
  },
];
const barrierStart = b1.text.indexOf("Isolation");

const r4401: ReportDetail = {
  report_id: "r-4401",
  site: "Rig 4",
  timestamp: "2026-08-20T09:00:00Z",
  source: "synthetic",
  report_text: b1.text,
  extracted_fields: {
    activity: spanField(overlapSpans, "activity", 0.91)!,
    hazard: spanField(overlapSpans, "hazard", 0.83),
    energy_type: labelField("stored/electrical energy", 0.86),
    exposure: labelField("direct_proximity", 0.88, spanOf(overlapSpans, "exposure")),
    barrier: {
      text: "Isolation",
      span: [barrierStart, barrierStart + "Isolation".length],
      confidence: 0.8,
    },
    barrier_status: labelField(
      "uncertain",
      0.79,
      spanOf(overlapSpans, "barrier_status")
    ),
    location: null,
    evidence_spans: [],
  },
  classification: {
    sif_potential: true,
    confidence: 0.91,
    bucket: "HIGH_CONF_SIF",
    lsr_tag: "Energy Isolation",
    justification:
      "Flagged as SIF-potential: stored/electrical energy present, isolation status uncertain, worker in direct proximity.",
    model_version: "baseline2-v0.3",
  },
  review_status: "pending",
};

/* ------------------------------------------------------------------ r-4402 */
const b2 = buildReport(
  `During {{activity|lifting operation with mobile crane}} at Plant C, {{exposure|no personnel were in the vicinity at the time}}. {{barrier_status|Exclusion zone was established and maintained throughout}}. No injury occurred.`
);
const r4402: ReportDetail = {
  report_id: "r-4402",
  site: "Plant C",
  timestamp: "2026-08-22T14:12:00Z",
  source: "synthetic",
  report_text: b2.text,
  extracted_fields: {
    activity: spanField(b2.spans, "activity", 0.9)!,
    hazard: null,
    energy_type: labelField("gravitational (suspended load)", 0.84),
    exposure: labelField("no_exposure", 0.9, spanOf(b2.spans, "exposure")),
    barrier: null,
    barrier_status: labelField(
      "confirmed_present",
      0.88,
      spanOf(b2.spans, "barrier_status")
    ),
    location: null,
    evidence_spans: [],
  },
  classification: {
    sif_potential: false,
    confidence: 0.89,
    bucket: "HIGH_CONF_NON_SIF",
    lsr_tag: "Safe Mechanical Lifting",
    justification:
      "Not SIF-potential: exclusion zone confirmed present and maintained, no personnel exposure at the time of the activity.",
    model_version: "baseline2-v0.3",
  },
  review_status: "confirmed",
};

/* ------------------------------------------------------------------ r-4403 */
const b3 = buildReport(
  `During {{activity|hot work / welding near process line}} at Rig 7, {{exposure|a technician was inside the equipment when work commenced}}. {{barrier_status|Permit was raised but supervisor sign-off could not be located}}. No injury occurred. Mazdoor ko turant hataya gaya.`
);
const r4403: ReportDetail = {
  report_id: "r-4403",
  site: "Rig 7",
  timestamp: "2026-08-25T07:40:00Z",
  source: "synthetic",
  report_text: b3.text,
  extracted_fields: {
    activity: spanField(b3.spans, "activity", 0.72)!,
    hazard: null,
    energy_type: labelField("thermal (hot work)", 0.68),
    exposure: labelField("direct_proximity", 0.7, spanOf(b3.spans, "exposure")),
    barrier: null,
    barrier_status: labelField(
      "uncertain",
      0.64,
      spanOf(b3.spans, "barrier_status")
    ),
    location: null,
    evidence_spans: [],
  },
  classification: {
    sif_potential: true,
    confidence: 0.58,
    bucket: "LOW_CONF_REVIEW",
    lsr_tag: "Hot Work",
    justification:
      "Low confidence: thermal energy likely present and exposure direct, but barrier status could not be resolved from the report text. Routed for human review.",
    model_version: "baseline2-v0.3",
  },
  review_status: "pending",
};

/* ------------------------------------------------------------------ r-4404 */
const b4 = buildReport(
  `{{activity|Routine equipment inspection}} carried out at Terminal A. Conditions noted as normal. No further detail provided.`
);
const r4404: ReportDetail = {
  report_id: "r-4404",
  site: "Terminal A",
  timestamp: "2026-08-28T11:05:00Z",
  source: "synthetic",
  report_text: b4.text,
  extracted_fields: {
    activity: spanField(b4.spans, "activity", 0.66)!,
    hazard: null,
    energy_type: labelField("low-energy/ergonomic", 0.55), // span:null — not located
    exposure: labelField("no_exposure", 0.52), // span:null
    barrier: null,
    barrier_status: labelField("absent_not_mentioned", 0.6), // span:null
    location: null,
    evidence_spans: [],
  },
  classification: {
    sif_potential: false,
    confidence: 0.44,
    bucket: "NEEDS_MORE_INFO",
    lsr_tag: "Work Authorisation",
    justification:
      "Insufficient information: the report does not describe energy source, barrier state, or personnel exposure. Follow-up with the site is required before classification.",
    model_version: "baseline2-v0.3",
  },
  review_status: "pending",
};

/* ------------------------------------------------------------------ r-4405 */
const b5 = buildReport(
  `During {{activity|scaffolding erection at height}} at Field Station 2, {{exposure|a worker was nearby but not directly in the hazard path}}. {{barrier_status|Work proceeded without a permit being sighted}}. Minor first aid case reported.`
);
const r4405: ReportDetail = {
  report_id: "r-4405",
  site: "Field Station 2",
  timestamp: "2026-09-01T16:30:00Z",
  source: "synthetic",
  report_text: b5.text,
  extracted_fields: {
    activity: spanField(b5.spans, "activity", 0.9)!,
    hazard: null,
    energy_type: labelField("fall from height", 0.85),
    exposure: labelField(
      "indirect_proximity",
      0.82,
      spanOf(b5.spans, "exposure")
    ),
    barrier: null,
    barrier_status: labelField(
      "absent_not_mentioned",
      0.87,
      spanOf(b5.spans, "barrier_status")
    ),
    location: null,
    evidence_spans: [],
  },
  classification: {
    sif_potential: true,
    confidence: 0.88,
    bucket: "HIGH_CONF_SIF",
    lsr_tag: "Working at Height",
    justification:
      "Flagged as SIF-potential: fall-from-height energy present, no permit control sighted, personnel in indirect proximity to the hazard path.",
    model_version: "baseline2-v0.3",
  },
  review_status: "pending",
};

/* ------------------------------------------------------------------ r-4406 */
/* Report WITH hazard evidence -> pipeline emits the buggy {label,...} shape.
   In live mode this id 500s; the fixture reproduces the broken shape so the
   client's graceful-degradation path is demoable offline too. */
const b6 = buildReport(
  `During {{activity|confined space entry for tank cleaning}} at Well Site B, {{exposure|a technician was inside the equipment when work commenced}}. {{barrier_status|Gas test reportedly done earlier in the shift, not re-verified}}. No injury occurred.`
);
const r4406: ReportDetail = {
  report_id: "r-4406",
  site: "Well Site B",
  timestamp: "2026-09-03T05:20:00Z",
  source: "synthetic",
  report_text: b6.text,
  extracted_fields: {
    activity: spanField(b6.spans, "activity", 0.89)!,
    // buggy shape emitted by sif_engine/pipeline.py (label instead of text)
    hazard: { label: "atmospheric/asphyxiation", confidence: 0.85, span: null },
    energy_type: labelField("atmospheric/asphyxiation", 0.86),
    exposure: labelField("direct_proximity", 0.86, spanOf(b6.spans, "exposure")),
    barrier: null,
    barrier_status: labelField(
      "uncertain",
      0.78,
      spanOf(b6.spans, "barrier_status")
    ),
    location: null,
    evidence_spans: [],
  } as ReportDetail["extracted_fields"],
  classification: {
    sif_potential: true,
    confidence: 0.9,
    bucket: "HIGH_CONF_SIF",
    lsr_tag: "Confined Space",
    justification:
      "Flagged as SIF-potential: asphyxiation atmosphere, gas test not re-verified before entry, technician inside the space.",
    model_version: "baseline2-v0.3",
  },
  review_status: "pending",
};

/* ------------------------------------------------------------------ r-4410 */
const b10 = buildReport(
  `During {{activity|pipeline pigging operation}} at Rig 4, {{exposure|personnel were in the general work area at the time}}. {{barrier_status|Exclusion zone markers were present but not actively enforced}}. Near miss — situation was corrected before escalation.`
);
const r4410: ReportDetail = {
  report_id: "r-4410",
  site: "Rig 4",
  timestamp: "2026-08-18T06:15:00Z",
  source: "synthetic",
  report_text: b10.text,
  extracted_fields: {
    activity: spanField(b10.spans, "activity", 0.74)!,
    hazard: null,
    energy_type: labelField("kinetic (line of fire)", 0.63),
    exposure: labelField(
      "indirect_proximity",
      0.61,
      spanOf(b10.spans, "exposure")
    ),
    barrier: null,
    barrier_status: labelField(
      "uncertain",
      0.59,
      spanOf(b10.spans, "barrier_status")
    ),
    location: null,
    evidence_spans: [],
  },
  classification: {
    sif_potential: true,
    confidence: 0.54,
    bucket: "LOW_CONF_REVIEW",
    lsr_tag: "Line of Fire",
    justification:
      "Low confidence: stored pressure and line-of-fire energy plausible, but exposure is indirect and barrier enforcement is ambiguous in the text. Routed for human review.",
    model_version: "baseline2-v0.3",
  },
  review_status: "pending",
};

/* ------------------------------------------------------------------ r-4411 */
const b11 = buildReport(
  `{{activity|Vehicle movement within plant premises}} at Well Site B reported during a routine walk-around. Speed and separation not described.`
);
const r4411: ReportDetail = {
  report_id: "r-4411",
  site: "Well Site B",
  timestamp: "2026-08-21T13:45:00Z",
  source: "synthetic",
  report_text: b11.text,
  extracted_fields: {
    activity: spanField(b11.spans, "activity", 0.7)!,
    hazard: null,
    energy_type: labelField("vehicular/motion", 0.5),
    exposure: labelField("indirect_proximity", 0.42),
    barrier: null,
    barrier_status: labelField("absent_not_mentioned", 0.55),
    location: null,
    evidence_spans: [],
  },
  classification: {
    sif_potential: false,
    confidence: 0.4,
    bucket: "NEEDS_MORE_INFO",
    lsr_tag: "Driving",
    justification:
      "Insufficient information: the report notes vehicle movement but does not describe proximity to personnel, speed, or separation controls. Follow-up with the site is required.",
    model_version: "baseline2-v0.3",
  },
  review_status: "pending",
};

/* ------------------------------------------------------------------ r-4412 */
const b12 = buildReport(
  `During {{activity|confined space entry for tank cleaning}} at Plant C, {{exposure|a technician was inside the equipment when work commenced}}. {{barrier_status|Gas test reportedly done earlier in the shift, not re-verified}}. No injury occurred.`
);
const r4412: ReportDetail = {
  report_id: "r-4412",
  site: "Plant C",
  timestamp: "2026-08-30T04:50:00Z",
  source: "synthetic",
  report_text: b12.text,
  extracted_fields: {
    activity: spanField(b12.spans, "activity", 0.8)!,
    hazard: null,
    energy_type: labelField("atmospheric/asphyxiation", 0.66),
    exposure: labelField(
      "direct_proximity",
      0.69,
      spanOf(b12.spans, "exposure")
    ),
    barrier: null,
    barrier_status: labelField(
      "uncertain",
      0.6,
      spanOf(b12.spans, "barrier_status")
    ),
    location: null,
    evidence_spans: [],
  },
  classification: {
    sif_potential: true,
    confidence: 0.61,
    bucket: "LOW_CONF_REVIEW",
    lsr_tag: "Confined Space",
    justification:
      "Low confidence: asphyxiation atmosphere and direct exposure indicated, but gas-test recency is unclear. One reviewer has already recorded a correction on this report.",
    model_version: "baseline2-v0.3",
  },
  review_status: "pending",
};

/* ------------------------------------------------------------------ r-4413 */
const b13 = buildReport(
  `During {{activity|lifting operation with mobile crane}} at Terminal A, {{exposure|the contractor was positioned directly beneath the suspended load}} briefly. {{barrier_status|Permit was raised but supervisor sign-off could not be located}}. No injury occurred.`
);
const r4413: ReportDetail = {
  report_id: "r-4413",
  site: "Terminal A",
  timestamp: "2026-09-02T10:05:00Z",
  source: "synthetic",
  report_text: b13.text,
  extracted_fields: {
    activity: spanField(b13.spans, "activity", 0.82)!,
    hazard: null,
    energy_type: labelField("gravitational (suspended load)", 0.7),
    exposure: labelField(
      "direct_proximity",
      0.72,
      spanOf(b13.spans, "exposure")
    ),
    barrier: null,
    barrier_status: labelField(
      "uncertain",
      0.63,
      spanOf(b13.spans, "barrier_status")
    ),
    location: null,
    evidence_spans: [],
  },
  classification: {
    sif_potential: true,
    confidence: 0.66,
    bucket: "LOW_CONF_REVIEW",
    lsr_tag: "Safe Mechanical Lifting",
    justification:
      "Low confidence: suspended-load energy and direct line of fire suggested, but the exposure duration and sign-off status are ambiguous. Routed for human review.",
    model_version: "baseline2-v0.3",
  },
  review_status: "pending",
};

export const REPORT_FIXTURES: Record<string, ReportDetail> = {
  "r-4401": r4401,
  "r-4402": r4402,
  "r-4403": r4403,
  "r-4404": r4404,
  "r-4405": r4405,
  "r-4406": r4406,
  "r-4410": r4410,
  "r-4411": r4411,
  "r-4412": r4412,
  "r-4413": r4413,
};

export const REPORT_LIST_ORDER = [
  "r-4401",
  "r-4413",
  "r-4405",
  "r-4406",
  "r-4412",
  "r-4403",
  "r-4404",
  "r-4411",
  "r-4410",
  "r-4402",
];

/** Buckets the backend routes into the review queue. */
export const REVIEW_QUEUE_BUCKETS = ["LOW_CONF_REVIEW", "NEEDS_MORE_INFO"];

/**
 * Reports where a second independent reviewer has already logged a matching
 * label — so the next matching action from a different reviewer trips the
 * 2-reviewer-agreement gate and returns promoted_to_training_queue: true.
 */
export const PROMOTES_ON_ACTION = new Set<string>(["r-4412"]);
